version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/marpio/img-store

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - run:
          name: Run unit tests
          command: |
            go test ./... | tee ${TEST_RESULTS}/test.out
      - run: 
          name: Build cli and web
          command: |
            go build ./cmd/...

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results