version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/marpio/img-store

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: 
          name: Build cli and web
          command: |
            go build ./cmd/...
      - run: mkdir -p $TEST_RESULTS
      - run:
          name: Run unit tests and code cov
          command: |
            set -e
            echo "" > ${TEST_RESULTS}/coverage.txt
            for d in $(go list ./... | grep -v vendor); do
                go test -race -coverprofile=profile.out -covermode=atomic $d | tee test.out
                if [ -f test.out ]; then
                    cat test.out >> ${TEST_RESULTS}/tests.out
                    rm test.out
                fi
                if [ -f profile.out ]; then
                    cat profile.out >> ${TEST_RESULTS}/coverage.txt
                    rm profile.out
                fi
            done
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
      - run:
          name: Upload coverage report to codecov.io
          command: |
            bash <(curl -s https://codecov.io/bash) -f ${TEST_RESULTS}/coverage.txt
      - add_ssh_keys:
          fingerprints:
            - "1c:bc:c4:38:d7:11:55:bb:d5:8f:05:8a:dc:02:86:f2"
      - run:
          name: Add doku to known_hosts
          command: |
            ssh-keyscan -H {DOKKU_HOSTNAME} >> ~/.ssh/known_hosts
      - run:
          name: Deploy Master to Dokku
          command: |
            git push --force git@${DOKKU_HOSTNAME}:foto.git HEAD:refs/heads/master
      - setup_remote_docker:
          version: 17.07.0-ce
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t   marpiot/pics:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push marpiot/pics:$TAG

          