version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/marpio/img-store

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - run:
          name: Run unit tests and code cov
          command: |
            set -e
            echo "" > ${TEST_RESULTS}/coverage.txt
            for d in $(go list ./... | grep -v vendor); do
                go test -race -coverprofile=profile.out -covermode=atomic $d | tee ${TEST_RESULTS}/test.out
                if [ -f profile.out ]; then
                    cat profile.out >> ${TEST_RESULTS}/coverage.txt
                    rm profile.out
                fi
            done
      - run: 
          name: Build cli and web
          command: |
            go build ./cmd/...

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results