version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/marpio/mirror

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: 
          name: Build cli and web
          command: |
            go build ./cmd/...
      - run: mkdir -p $TEST_RESULTS
      - run:
          name: Run unit tests and code cov
          command: |
            set -e
            echo "" > ${TEST_RESULTS}/coverage.txt
            for d in $(go list ./... | grep -v vendor); do
                go test -race -coverprofile=profile.out -covermode=atomic $d | tee test.out
                if [ -f test.out ]; then
                    cat test.out >> ${TEST_RESULTS}/tests.out
                    rm test.out
                fi
                if [ -f profile.out ]; then
                    cat profile.out >> ${TEST_RESULTS}/coverage.txt
                    rm profile.out
                fi
            done
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
      - run:
          name: Upload coverage report to codecov.io
          command: |
            bash <(curl -s https://codecov.io/bash) -f ${TEST_RESULTS}/coverage.txt
      - setup_remote_docker:
          version: 17.07.0-ce
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t   marpiot/mirror:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push marpiot/mirror:$TAG
  deploy:
    docker:
      - image: governmentpaas/git-ssh:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "9e:11:da:85:c7:5c:36:9d:3a:04:a0:2e:f8:98:90:34"
      - run:
          name: Deploy Master to Dokku
          command: |
            ssh-keyscan -H ${DOKKU_HOSTNAME} >> ~/.ssh/known_hosts
            NR=$((CIRCLE_BUILD_NUM-1))
            TAG=0.1.$NR
            ssh marpio@${DOKKU_HOSTNAME} "docker pull marpiot/mirror:$TAG && docker tag marpiot/mirror:$TAG dokku/foto:$TAG && dokku tags:deploy foto $TAG"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master    
           